---
title: "5_societal_scale"
output: html_document
---


```{r}
library(pacman)
p_load(brms, tidyverse, here)
set.seed(12532)

d <- read_csv(here("data","preprocessed","answerset_large.csv"), show_col_types = FALSE)
d %>% glimpse()
```

```{r}

priors <- c(
  prior(normal(0, 1.5), class = Intercept), 
  prior(normal(0, 1),   class = b),
  prior(exponential(1), class = sd) 
)

```


Model 1: marker ~ state
Extra-ritual in-group markers (credible)

```{r}

fit1 <- brm(extra_ritual_group_markers ~ 1 + state + year_scaled + (1|world_region), 
            data = d, family = bernoulli("logit"), prior = priors,
             chains = 4, iter = 4000, warmup = 2000, cores = 4,
             control = list(adapt_delta = 0.99),
             seed = 51252, backend = "cmdstanr", silent = 2)

summary(fit1)

```

Model 2: marker ~ state
Permanent scarring (not credible)

```{r}

fit2 <- brm(permanent_scarring ~ 1 + state + year_scaled + (1|world_region), 
            data = d, family = bernoulli("logit"), prior = priors,
             chains = 4, iter = 4000, warmup = 2000, cores = 4,
             control = list(adapt_delta = 0.99),
             seed = 51252, backend = "cmdstanr", silent = 2)

summary(fit2)

```

Model 3: marker ~ state + violent_external
Extra-ritual in-group markers

```{r}

fit3 <- brm(extra_ritual_group_markers ~ 1 + state + violent_external + year_scaled + (1|world_region), 
            data = d, family = bernoulli("logit"), prior = priors,
             chains = 4, iter = 4000, warmup = 2000, cores = 4,
             control = list(adapt_delta = 0.99),
             seed = 51252, backend = "cmdstanr", silent = 2)

summary(fit3)

```

Model 4: marker ~ state + violent_external
Extra-ritual in-group markers (not credible)

```{r}

fit4 <- brm(permanent_scarring ~ 1 + state + violent_external + year_scaled + (1|world_region), 
            data = d, family = bernoulli("logit"), prior = priors,
             chains = 4, iter = 4000, warmup = 2000, cores = 4,
             control = list(adapt_delta = 0.99),
             seed = 51252, backend = "cmdstanr", silent = 2)

summary(fit4)

```

Model 5: violent_external ~ state 

```{r}

fit5 <- brm(violent_external ~ 1 + state + year_scaled + (1|world_region), 
            data = d, family = bernoulli("logit"), prior = priors,
             chains = 4, iter = 4000, warmup = 2000, cores = 4,
             control = list(adapt_delta = 0.99),
             seed = 51252, backend = "cmdstanr", silent = 2)

summary(fit5)

```

BRMS hypothesis

```{r}

h_fit3_state <- hypothesis(fit3, "state < 0", alpha = 0.025)
h_fit3_conflict <- hypothesis(fit3, "violent_external > 0", alpha = 0.025)
h_fit4_state <- hypothesis(fit4, "state < 0", alpha = 0.025)
h_fit4_conflict <- hypothesis(fit4, "violent_external > 0", alpha = 0.025)
h_fit5_state <- hypothesis(fit5, "state < 0", alpha = 0.025)

```

Check each:

```{r}

h_fit3_state

```

```{r}

h_fit3_conflict

```

```{r}

h_fit3_state

```


```{r}

h_fit4_conflict

```

```{r}

h_fit4_state

```



